// Generated by gencpp from file srv_client_server/AddInts.msg
// DO NOT EDIT!


#ifndef SRV_CLIENT_SERVER_MESSAGE_ADDINTS_H
#define SRV_CLIENT_SERVER_MESSAGE_ADDINTS_H

#include <ros/service_traits.h>


#include <srv_client_server/AddIntsRequest.h>
#include <srv_client_server/AddIntsResponse.h>


namespace srv_client_server
{

struct AddInts
{

typedef AddIntsRequest Request;
typedef AddIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddInts
} // namespace srv_client_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srv_client_server::AddInts > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::srv_client_server::AddInts&) { return value(); }
};

template<>
struct DataType< ::srv_client_server::AddInts > {
  static const char* value()
  {
    return "srv_client_server/AddInts";
  }

  static const char* value(const ::srv_client_server::AddInts&) { return value(); }
};


// service_traits::MD5Sum< ::srv_client_server::AddIntsRequest> should match
// service_traits::MD5Sum< ::srv_client_server::AddInts >
template<>
struct MD5Sum< ::srv_client_server::AddIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srv_client_server::AddInts >::value();
  }
  static const char* value(const ::srv_client_server::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv_client_server::AddIntsRequest> should match
// service_traits::DataType< ::srv_client_server::AddInts >
template<>
struct DataType< ::srv_client_server::AddIntsRequest>
{
  static const char* value()
  {
    return DataType< ::srv_client_server::AddInts >::value();
  }
  static const char* value(const ::srv_client_server::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srv_client_server::AddIntsResponse> should match
// service_traits::MD5Sum< ::srv_client_server::AddInts >
template<>
struct MD5Sum< ::srv_client_server::AddIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srv_client_server::AddInts >::value();
  }
  static const char* value(const ::srv_client_server::AddIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv_client_server::AddIntsResponse> should match
// service_traits::DataType< ::srv_client_server::AddInts >
template<>
struct DataType< ::srv_client_server::AddIntsResponse>
{
  static const char* value()
  {
    return DataType< ::srv_client_server::AddInts >::value();
  }
  static const char* value(const ::srv_client_server::AddIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRV_CLIENT_SERVER_MESSAGE_ADDINTS_H
